feat: update ci.yaml

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -9,11 +9,50 @@ on:
   pull_request:
 
 jobs:
-  lint:
+  formatting:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4
+
+      - name: Format
+        uses: cpp-linter/cpp-linter-action@v2
+        id: formatter
+        with:
+          version: 11
+          style: file
+          tidy-checks: '-*' # only formatting
+
+      - name: Fail?
+        if: steps.formatter.outputs.checks-failed > 0
+        run: echo "Some files failed the formatting checks!" && exit 1
+
+  lint:
+    needs: formatting
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v4
+
+      - name: Set up Python
+        uses: actions/setup-python@v4
+        with:
+          python-version: '3.10'
+
+      - name: Install Dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r requirements.txt
+
+      - name: Create Conan build
+        run: |
+          conan profile detect --force
+          conan install . --output-folder=build --build=missing
+
+      - name: Build with CMake
+        run: |
+          cmake -S . -B build --preset conan-release -DCMAKE_BUILD_TYPE=Release
+          cmake --build build
 
       - name: Lint
         uses: cpp-linter/cpp-linter-action@v2
@@ -21,14 +60,15 @@ jobs:
         with:
           version: 11
           style: file
-          tidy-checks: '' # use .clang-tidy
+          tidy-checks: '' # force the use of .clang-tidy
+          database: 'build'
 
-      - name: Fail test
+      - name: Fail?
         if: steps.linter.outputs.checks-failed > 0
         run: echo "Some files failed the linting checks!" && exit 1
 
   test:
-    needs: lint
+    needs: formatting
     strategy:
       fail-fast: false
       matrix:
